from __future__ import annotations

from typing import Any

from ..models import Address, TokenResponse, User, UserAndCompany

class SyncUsersClient:
    def __init__(self, client: Any) -> None: ...
    def get(self, id: int) -> User: ...
    def get_address(self, id: int) -> Address: ...
    def get_companies(self) -> list[UserAndCompany]: ...
    def authenticate(self) -> TokenResponse: ...
    def refresh_token(self, refresh_token: str) -> TokenResponse: ...

class AsyncUsersClient:
    def __init__(self, client: Any) -> None: ...
    async def get(self, id: int) -> User: ...
    async def get_address(self, id: int) -> Address: ...
    async def get_companies(self) -> list[UserAndCompany]: ...
    async def authenticate(self) -> TokenResponse: ...
    async def refresh_token(self, refresh_token: str) -> TokenResponse: ...
