from __future__ import annotations

from typing import Any

from henrri_connect.models import Address, Contact, Customer, PagedListResponse

class SyncCustomersClient:
    def __init__(self, client: Any) -> None: ...
    def list_customers(
        self,
        *,
        page: int = ...,
        limit: int = ...,
        search: str | None = ...,
        sort_by: str | None = ...,
        sort_order: str | None = ...,
        min_id: int | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
    ) -> PagedListResponse[Customer]: ...
    def add(self, customer: Customer) -> Customer: ...
    def get_best_sales(
        self,
        *,
        page: int = ...,
        limit: int = ...,
        search: str | None = ...,
        sort_by: str | None = ...,
        sort_order: str | None = ...,
    ) -> PagedListResponse[Customer]: ...
    def get(self, customer_id: int) -> Customer: ...
    def modify(self, customer_id: int, customer: Customer) -> Customer: ...
    def delete(self, customer_id: int) -> None: ...
    def get_address(self, customer_id: int) -> Address: ...
    def list_contacts(self, customer_id: int) -> list[Contact]: ...
    def add_contact(self, customer_id: int, contact: Contact) -> Contact: ...
    def get_contact(self, customer_id: int, contact_id: int) -> Contact: ...
    def modify_contact(self, customer_id: int, contact_id: int, contact: Contact) -> Contact: ...
    def delete_contact(self, customer_id: int, contact_id: int) -> None: ...

class AsyncCustomersClient:
    def __init__(self, client: Any) -> None: ...
    async def list_customers(
        self,
        *,
        page: int = ...,
        limit: int = ...,
        search: str | None = ...,
        sort_by: str | None = ...,
        sort_order: str | None = ...,
        min_id: int | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
    ) -> PagedListResponse[Customer]: ...
    async def add(self, customer: Customer) -> Customer: ...
    async def get_best_sales(
        self,
        *,
        page: int = ...,
        limit: int = ...,
        search: str | None = ...,
        sort_by: str | None = ...,
        sort_order: str | None = ...,
    ) -> PagedListResponse[Customer]: ...
    async def get(self, customer_id: int) -> Customer: ...
    async def modify(self, customer_id: int, customer: Customer) -> Customer: ...
    async def delete(self, customer_id: int) -> None: ...
    async def get_address(self, customer_id: int) -> Address: ...
    async def list_contacts(self, customer_id: int) -> list[Contact]: ...
    async def add_contact(self, customer_id: int, contact: Contact) -> Contact: ...
    async def get_contact(self, customer_id: int, contact_id: int) -> Contact: ...
    async def modify_contact(
        self, customer_id: int, contact_id: int, contact: Contact
    ) -> Contact: ...
    async def delete_contact(self, customer_id: int, contact_id: int) -> None: ...
