from __future__ import annotations

from typing import Any

from henrri_connect.models import MonthlyRevenueStatistics, RevenueStatistics

class SyncRevenuesClient:
    def __init__(self, client: Any) -> None: ...
    def get_annual(self, year: int) -> RevenueStatistics: ...
    def get_monthly(self, year: int) -> list[MonthlyRevenueStatistics]: ...

class AsyncRevenuesClient:
    def __init__(self, client: Any) -> None: ...
    async def get_annual(self, year: int) -> RevenueStatistics: ...
    async def get_monthly(self, year: int) -> list[MonthlyRevenueStatistics]: ...
