from __future__ import annotations

from typing import Any

from henrri_connect.models import DocumentType, ListResponse

class SyncDocumentTypesClient:
    def __init__(self, client: Any) -> None: ...
    def list_document_types(self) -> ListResponse[DocumentType]: ...

class AsyncDocumentTypesClient:
    def __init__(self, client: Any) -> None: ...
    async def list_document_types(self) -> ListResponse[DocumentType]: ...
