from __future__ import annotations

from typing import Any

from henrri_connect.models import ListResponse, Unit

class SyncUnitsClient:
    def __init__(self, client: Any) -> None: ...
    def list_units(self) -> ListResponse[Unit]: ...
    def add(self, unit: Unit) -> Unit: ...
    def get(self, id: int) -> Unit: ...

class AsyncUnitsClient:
    def __init__(self, client: Any) -> None: ...
    async def list_units(self) -> ListResponse[Unit]: ...
    async def add(self, unit: Unit) -> Unit: ...
    async def get(self, id: int) -> Unit: ...
