class HenrriError(Exception): ...

class HenrriHTTPError(HenrriError):
    status_code: int
    def __init__(self, status_code: int, message: str) -> None: ...

class HenrriAuthError(HenrriHTTPError): ...
class HenrriForbiddenError(HenrriHTTPError): ...
class HenrriNotFoundError(HenrriHTTPError): ...
class HenrriValidationError(HenrriHTTPError): ...
class HenrriServerError(HenrriHTTPError): ...
