from __future__ import annotations

from typing import Any

from henrri_connect.models import (
    Document,
    ListResponse,
    PagedListResponse,
    PaymentMilestone,
    PdfUrlResponse,
    TaxDetailArray,
    ValidateDocumentRequest,
)

class SyncDocumentsClient:
    def __init__(self, client: Any) -> None: ...
    def list_documents(
        self,
        *,
        page: int = ...,
        limit: int = ...,
        search: str | None = ...,
        sort_by: str | None = ...,
        sort_order: str | None = ...,
        document_type_id: int | None = ...,
        customer_id: int | None = ...,
        state: str | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        min_id: int | None = ...,
    ) -> PagedListResponse[Document]: ...
    def add(self, document: Document) -> Document: ...
    def get(self, id: int) -> Document: ...
    def get_with_all(self, id: int) -> Document: ...
    def get_all_included(self, id: int) -> Document: ...
    def modify(self, id: int, document: Document) -> Document: ...
    def delete(self, id: int) -> None: ...
    def get_tax_details(self, id: int) -> TaxDetailArray: ...
    def validate(self, id: int, request: ValidateDocumentRequest) -> Document: ...
    def get_pdf_url(self, id: int) -> PdfUrlResponse: ...
    def get_pdf_bytes(self, id: int) -> bytes: ...
    def get_pdf_file(self, id: int, guid: str) -> bytes: ...
    def get_display(self, id: int) -> Document: ...
    def get_payment_milestones(self, document_id: int) -> ListResponse[PaymentMilestone]: ...
    def finalize(self, id: int) -> Document: ...
    def transform_to_invoice(self, id: int) -> Document: ...
    def get_next_quote_batch(self) -> object: ...
    def list_with_selected_fields(
        self,
        *,
        page: int = ...,
        limit: int = ...,
        fields: str | None = ...,
        **kwargs: object,
    ) -> PagedListResponse[Document]: ...

class AsyncDocumentsClient:
    def __init__(self, client: Any) -> None: ...
    async def list(
        self,
        *,
        page: int = ...,
        limit: int = ...,
        search: str | None = ...,
        sort_by: str | None = ...,
        sort_order: str | None = ...,
        document_type_id: int | None = ...,
        customer_id: int | None = ...,
        state: str | None = ...,
        from_date: str | None = ...,
        to_date: str | None = ...,
        min_id: int | None = ...,
    ) -> PagedListResponse[Document]: ...
    async def add(self, document: Document) -> Document: ...
    async def get(self, id: int) -> Document: ...
    async def get_with_all(self, id: int) -> Document: ...
    async def get_all_included(self, id: int) -> Document: ...
    async def modify(self, id: int, document: Document) -> Document: ...
    async def delete(self, id: int) -> None: ...
    async def get_tax_details(self, id: int) -> TaxDetailArray: ...
    async def validate(self, id: int, request: ValidateDocumentRequest) -> Document: ...
    async def get_pdf_url(self, id: int) -> PdfUrlResponse: ...
    async def get_pdf_bytes(self, id: int) -> bytes: ...
    async def get_pdf_file(self, id: int, guid: str) -> bytes: ...
    async def get_display(self, id: int) -> Document: ...
    async def get_payment_milestones(self, document_id: int) -> ListResponse[PaymentMilestone]: ...
    async def finalize(self, id: int) -> Document: ...
    async def transform_to_invoice(self, id: int) -> Document: ...
    async def get_next_quote_batch(self) -> object: ...
    async def list_with_selected_fields(
        self,
        *,
        page: int = ...,
        limit: int = ...,
        fields: str | None = ...,
        **kwargs: object,
    ) -> PagedListResponse[Document]: ...
