from __future__ import annotations

from typing import Any
from ..models import Address, Company

class SyncCompaniesClient:
    def __init__(self, client: Any) -> None: ...
    def get(self, company_id: int) -> Company: ...
    def get_address(self, company_id: int) -> Address: ...

class AsyncCompaniesClient:
    def __init__(self, client: Any) -> None: ...
    async def get(self, company_id: int) -> Company: ...
    async def get_address(self, company_id: int) -> Address: ...
