from __future__ import annotations

from typing import Any

from henrri_connect.models import DocumentLine, ListResponse

class SyncDocumentLinesClient:
    def __init__(self, client: Any) -> None: ...
    def list_document_lines(self, document_id: int) -> ListResponse[DocumentLine]: ...
    def add(self, document_id: int, line: DocumentLine) -> DocumentLine: ...
    def get(self, document_id: int, id: int) -> DocumentLine: ...
    def modify(self, document_id: int, id: int, line: DocumentLine) -> DocumentLine: ...
    def delete(self, document_id: int, id: int) -> None: ...
    def move(self, document_id: int, id: int, to: int) -> None: ...

class AsyncDocumentLinesClient:
    def __init__(self, client: Any) -> None: ...
    async def list_document_lines(self, document_id: int) -> ListResponse[DocumentLine]: ...
    async def add(self, document_id: int, line: DocumentLine) -> DocumentLine: ...
    async def get(self, document_id: int, id: int) -> DocumentLine: ...
    async def modify(self, document_id: int, id: int, line: DocumentLine) -> DocumentLine: ...
    async def delete(self, document_id: int, id: int) -> None: ...
    async def move(self, document_id: int, id: int, to: int) -> None: ...
