from __future__ import annotations

from typing import Any

class SyncSecuresClient:
    def __init__(self, client: Any) -> None: ...
    def hello_world(self) -> str: ...

class AsyncSecuresClient:
    def __init__(self, client: Any) -> None: ...
    async def hello_world(self) -> str: ...
